### PR TITLE
States snippets

### PR DESCRIPTION
**Pull request by atornity**
added snippets for:
- State and NextState resource
- States derive enum

state and states are almost identical but that's how it's named in bevy so 🤷‍♀️

### CODE REVIEW

**Comment by rendaoer** [comment]
Great, looks like what I want to do. but the author looks busy

**Comment by maxsroka** [comment]
In [this example code](https://docs.rs/bevy/0.10.1/bevy/prelude/trait.States.html#example) in the docs, the `States` enum also has the `Copy` trait. Shouldn't it be in the template? I'm not too familiar with states.

**Comment by atornity** [comment]
> In [this example code](https://docs.rs/bevy/0.10.1/bevy/prelude/trait.States.html#example) in the docs, the `States` enum also has the `Copy` trait. Shouldn't it be in the template? I'm not too familiar with states.

`Copy` is not required but I think we could probably add it anyways unless rust fmt wraps the code when we include one more derive lol that'd be hella ugly

**Comment by rendaoer** [comment]
It is not a good idea to let type variables be freely copied at will, it is not necessary, why can't users add it again?

**Pull request closed without merging**
