### PR TITLE
add system set & icon

### PR DESCRIPTION
**Pull request by rendaoer**
Probably added system set and plug-in icon

### CODE REVIEW

**Comment by rendaoer** [comment]
Probably because of prettier formatting, git said that it seems to have changed, but in fact only the icon and two snippets were added.

**Comment by rendaoer** [comment]
Sorry, you didn't reply for a long time ago, so tried to create a plugin by myself. But I don't think it's very good, it was deleted a long time ago. Please forgive me for doing this~

**Comment by maxsroka** [comment]
There are too many changes at once. You may use the `Save without Formatting` command in VSCode.

**Comment by rendaoer** [comment]
Forget it, I don't know what I'm thinking

**Pull request closed without merging**
